---
version: "3"

dotenv:
  - ".env"

interval: 500ms

vars:
  PORT: $PORT

tasks:
  portainer:
    desc: runs portainer container
    cmds:
      - cd portainer && docker compose up

  ngnix:
    desc: runs ngnix container
    cmds:
      - cd ngnix && docker compose up
